import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import AppHeader from '../components/sections/appHeader';

const Home = () => {
    const headerLeftColumnContent = () => <h1>Hello Dere</h1>;
    const headerRightColumnContent = () => <h2>Right Column</h2>;

    return (
        <>
            <Head>
                <title>Rank Fuse Digital Marketing</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <AppHeader
                leftColumnContent={headerLeftColumnContent()}
                rightColumnContent={headerRightColumnContent()}
            />

            <main>
                <p>
                    <ul>
                        <li>
                            <Link href="/">
                                <a>Home</a>
                            </Link>
                        </li>
                        <li>
                            <Link href="/seo-services">
                                <a>Seo Services</a>
                            </Link>
                        </li>
                        <li>
                            <Link href="/web-design-and-development">
                                <a>Web Design and Development</a>
                            </Link>
                        </li>
                        <li>
                            <Link href="/seo-content">
                                <a>Seo Content</a>
                            </Link>
                        </li>
                    </ul>
                    <ul>
                        <li>Framer Motion</li>
                        <li>React Lottie + Animated Icons?</li>
                        <li>Theme UI?</li>
                    </ul>
                </p>
            </main>
        </>
    );
};

export default Home;
