/** @jsxImportSource theme-ui */
import Head from 'next/head';
import Image from 'next/image';
import { Button, useColorMode } from 'theme-ui';

import AppHeader from '../components/sections/appHeader';
import ServicesBenefitsRow from '../components/sections/appServiceBenefitsRow';
import TwoColumnVector from '../components/layout/twoColumnVector';

import headerDevices from '../public/images/homepage-header-devices.png';

const Home = () => {
    return (
        <>
            <Head>
                <title>Rank Fuse Digital Marketing</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <AppHeader
                leftColumnContent={HeaderLeftColumnContent()}
                rightColumnContent={HeaderRightColumnContent()}
            />

            <main>
                <ServicesBenefitsRow />
                <TwoColumnVector
                    vectorSide={'right'}
                    leftColumnContent={HeaderLeftColumnContent()}
                    rightColumnContent={HeaderRightColumnContent()}
                    sectionName={'testing'}
                />
                <div>
                    <ul>
                        <li>Framer Motion</li>
                        <li>React Lottie + Animated Icons?</li>
                        <li>Theme UI?</li>
                    </ul>
                </div>
            </main>
        </>
    );
};

const HeaderLeftColumnContent = () => {
    const [mode, setMode] = useColorMode();

    return (
        <div
            sx={{
                paddingTop: ['125px', '100px', '50px', '30px', '30px'],
                paddingBottom: ['150px', '225px', '30px', '30px', '30px'],
                paddingLeft: ['0px', '6%', '0px', '0px', '0px'],
                paddingRight: ['0px', '12%', '0px', '25px', '50px'],
            }}
        >
            <h1
                sx={{
                    variant: 'text.h1',
                    color: '#fff',
                }}
            >
                Rank Higher,
                <br /> Convert More,
                <br /> & Engage with Users
            </h1>
            <h4
                sx={{
                    variant: 'text.h4',
                    color: '#fff',
                    marginTop: 8,
                    marginBottom: 11,
                    fontSize: '24px',
                }}
            >
                We help businesses grow through high quality SEO, targeted
                content, and engaging websites.
            </h4>
            <Button variant="light" onClick={() => setMode('black')}>
                I Want To...
            </Button>
        </div>
    );
};

const HeaderRightColumnContent = () => {
    return (
        <>
            <div
                sx={{
                    display: 'grid',
                    justifyItems: 'center',
                    position: 'relative',
                    pb: '30px',
                }}
                className="boxShadowRight"
            >
                <Image
                    alt="Laptop with overlaying SEO metrics"
                    src={headerDevices}
                    width={541}
                    height={399}
                    quality={100}
                />
            </div>
        </>
    );
};

export default Home;
