/** @jsxImportSource theme-ui */
import Head from 'next/head';
import { useEffect } from 'react';

import { Button, useColorMode } from 'theme-ui';

import AppHeader from '../components/sections/appHeader';

const Home = () => {
    return (
        <>
            <Head>
                <title>Rank Fuse Digital Marketing</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <AppHeader
                leftColumnContent={HeaderLeftColumnContent()}
                rightColumnContent={HeaderRightColumnContent()}
            />

            <main>
                <div>
                    <ul>
                        <li>Framer Motion</li>
                        <li>React Lottie + Animated Icons?</li>
                        <li>Theme UI?</li>
                    </ul>
                </div>
            </main>
        </>
    );
};

const HeaderLeftColumnContent = () => {
    const [mode, setMode] = useColorMode();

    useEffect(() => {
        console.log(mode);
    }, [mode]);

    return (
        <>
            <h1
                sx={{
                    variant: 'text.h1',
                    color: '#fff',
                }}
            >
                Rank Higher,
                <br /> Convert More,
                <br /> & Engage with Users
            </h1>
            <h4
                sx={{
                    variant: 'text.h4',
                    color: '#fff',
                    marginTop: 8,
                    marginBottom: 11,
                    fontSize: '24px',
                }}
            >
                We help businesses grow through high quality SEO, targeted
                content, and engaging websites.
            </h4>
            <Button variant="light" onClick={() => setMode('black')}>
                I Want To...
            </Button>
        </>
    );
};

const HeaderRightColumnContent = () => {
    return (
        <>
            <h2>Hello Dere</h2>
        </>
    );
};

export default Home;
