import Head from 'next/head';
import Link from 'next/link';

const WebDesignAndDevelopment = ({ title }) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Welcome to the Web Design/Dev page!</h1>

                <ul>
                    <li>
                        <Link href="/">
                            <a>Home</a>
                        </Link>
                    </li>
                    <li>
                        <Link href="/seo-services">
                            <a>Seo Services</a>
                        </Link>
                    </li>
                    <li>
                        <Link href="/web-design-and-development">
                            <a>Web Design and Development</a>
                        </Link>
                    </li>
                    <li>
                        <Link href="/seo-content">
                            <a>Seo Content</a>
                        </Link>
                    </li>
                </ul>
            </main>
        </div>
    );
};

export default WebDesignAndDevelopment;

export async function getStaticProps(context) {
    return {
        props: {
            title: 'Web Design & Development | Rank Fuse Digital Marketing',
        }, // will be passed to the page component as props
    };
}
