/* eslint-disable @next/next/no-img-element */
/** @jsxImportSource theme-ui */
import Head from 'next/head';
import Image from 'next/image';

import AppHeader from '../../components/sections/appHeader';
import headerDevices from '../../public/images/homepage-header-devices.png';
import { Button } from 'theme-ui';
import CheckListItem from '../../components/checkListItem';
import WebDevIntroStats from '../../components/sections/web-design-and-dev/webDevIntroStats';
import WebDevProcess from '../../components/sections/web-design-and-dev/webDevProcess';
import WebDesign from '../../components/sections/web-design-and-dev/webDesign';
import FastSites from '../../components/sections/web-design-and-dev/fastSites';
import HeadlessWordPress from '../../components/sections/web-design-and-dev/headlessWordPress';
import TestimonialCarousel from '../../components/sections/appTestimonialCarousel';

import CTARow from '../../components/sections/appCTARow';

const WebDesignAndDev = () => {
    return (
        <div>
            <Head>
                <title>
                    Web Design and Development | Rank Fuse Digital Marketing
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>

            <AppHeader
                leftColumnContent={WebDesignAndDevLeftColumn()}
                rightColumnContent={WebDesignAndDevRightColumn()}
            />

            <main>
                <WebDevIntroStats />
                <WebDevProcess />
                <TestimonialCarousel />
                <WebDesign />
                <FastSites />
                <HeadlessWordPress />
                <CTARow
                    heading="Stand Out in the Crowd"
                    subheading="Take advantage of our free tools"
                ></CTARow>
            </main>
        </div>
    );
};

export default WebDesignAndDev;

const WebDesignAndDevLeftColumn = () => {
    return (
        <div
            sx={{
                paddingTop: ['125px', '125px', '150px', '30px'],
                paddingBottom: ['150px', '150px', '175px', '30px'],
                paddingLeft: ['0px', '6%', '0px', '0px'],
                paddingRight: ['0px', '12%', '0px', '25px'],
            }}
        >
            <h1
                sx={{
                    variant: 'text.h1',
                    color: '#fff',
                    marginBottom: '20px',
                }}
            >
                Is Your Website<br></br>
                Not Performing?
            </h1>
            <CheckListItem bgColor="#fff" checkmarkColor="primary">
                <p sx={{ color: '#fff', fontSize: '24px', marginLeft: '10px' }}>
                    Double your site speed
                </p>
            </CheckListItem>
            <CheckListItem bgColor="#fff" checkmarkColor="primary">
                <p sx={{ color: '#fff', fontSize: '24px', marginLeft: '10px' }}>
                    Reach users on all devices
                </p>
            </CheckListItem>
            <CheckListItem bgColor="#fff" checkmarkColor="primary">
                <p sx={{ color: '#fff', fontSize: '24px', marginLeft: '10px' }}>
                    Increase your conversions
                </p>
            </CheckListItem>
            <Button variant="light" sx={{ marginTop: '20px' }}>
                Let&apos;s Work Together
            </Button>
        </div>
    );
};

const WebDesignAndDevRightColumn = () => {
    return (
        <div
            sx={{
                display: 'grid',
                justifyItems: 'center',
                position: 'relative',
                paddingX: '25px',
                paddingBottom: '75px',
            }}
            className="boxShadowRight"
        >
            <Image
                alt="Laptop with overlaying SEO metrics"
                src={headerDevices}
                width={541}
                height={399}
                quality={100}
            />
        </div>
    );
};
